/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.livr.views;

import javax.swing.JFrame;

/**
 *
 * @author victor
 */
public class ErrorDialog extends javax.swing.JDialog {


    /**
     * Creates new form ErrorDialog
     * @param parent
     * @param modal
     * @param titulo
     * @param mensagemErro
     */
    public ErrorDialog(JFrame parent, boolean modal, String titulo, String mensagemErro) {
        super(parent, modal);
        initComponents();
        lblTitulo.setText(titulo);
        lblMensagemErro.setText(mensagemErro);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlContent = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblMensagemErro = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Algo de Errado Não Está Certo");
        setMinimumSize(new java.awt.Dimension(450, 200));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 102, 102));
        lblTitulo.setText("Título");
        lblTitulo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.2;
        pnlContent.add(lblTitulo, gridBagConstraints);

        lblMensagemErro.setBackground(new java.awt.Color(255, 255, 255));
        lblMensagemErro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblMensagemErro.setForeground(new java.awt.Color(255, 102, 102));
        lblMensagemErro.setText("Mensagem de Erro");
        lblMensagemErro.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.5;
        pnlContent.add(lblMensagemErro, gridBagConstraints);

        btnOK.setBackground(new java.awt.Color(255, 102, 102));
        btnOK.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(255, 255, 255));
        btnOK.setText("CORRIGIR");
        btnOK.setBorder(null);
        btnOK.setBorderPainted(false);
        btnOK.setFocusPainted(false);
        btnOK.setFocusable(false);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.3;
        pnlContent.add(btnOK, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        getContentPane().add(pnlContent, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblMensagemErro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
