/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.livr.views.boundary;

import static br.com.livr.statics.Sessao.getGoleirosPorTime;
import static br.com.livr.statics.Sessao.getJogadoresPorTime;
import br.com.livr.views.control.MainWindowController;
import br.com.livr.views.control.MainWindowListController;

/**
 *
 * @author victor
 */
public class MainWindow extends javax.swing.JFrame {

    private final MainWindowController mainWindowController = new MainWindowController(this);

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        MainWindowListController.initListasJogadores();
        listBatedoresPenaltis.setListData(MainWindowListController.getNomesBatedoresPenaltis());
        listBatedoresPenaltis.addListSelectionListener(new MainWindowListController(getJogadoresPorTime()));
        listGoleiros.setListData(MainWindowListController.getNomesGoleiros());
        listGoleiros.addListSelectionListener(new MainWindowListController(getGoleirosPorTime()));
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        separator = new javax.swing.JLabel();
        cadastroSectionTitle = new javax.swing.JLabel();
        selectedIndicator = new javax.swing.JLabel();
        closeButton = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        lblSeuNome = new javax.swing.JLabel();
        lblSuaEquipe = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEquipe = new javax.swing.JTextField();
        linha01 = new javax.swing.JLabel();
        linha02 = new javax.swing.JLabel();
        scrollPaneListaGoleiros = new javax.swing.JScrollPane();
        listGoleiros = new javax.swing.JList<>();
        lblGoleirosList = new javax.swing.JLabel();
        lblQuantidadeGoleiros = new javax.swing.JLabel();
        lblBatedoresDePenaltisList = new javax.swing.JLabel();
        scrollPaneListaBatedoresPenaltis = new javax.swing.JScrollPane();
        listBatedoresPenaltis = new javax.swing.JList<>();
        lblQuantidadeBatedoresDePenaltis = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penalty Fever");
        setBackground(new java.awt.Color(15, 89, 94));
        setUndecorated(true);

        header.setBackground(new java.awt.Color(35, 182, 132));

        title.setFont(new java.awt.Font("ADAM.CG PRO", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Inscreva seu time");

        separator.setBackground(new java.awt.Color(15, 89, 94));
        separator.setForeground(new java.awt.Color(15, 89, 94));
        separator.setText(".");
        separator.setOpaque(true);

        cadastroSectionTitle.setFont(new java.awt.Font("ADAM.CG PRO", 1, 18)); // NOI18N
        cadastroSectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        cadastroSectionTitle.setText("CADASTRO");

        selectedIndicator.setBackground(new java.awt.Color(15, 89, 94));
        selectedIndicator.setForeground(new java.awt.Color(15, 89, 94));
        selectedIndicator.setText(".");
        selectedIndicator.setOpaque(true);

        closeButton.setFont(new java.awt.Font("ADAM.CG PRO", 1, 24)); // NOI18N
        closeButton.setForeground(new java.awt.Color(4, 61, 93));
        closeButton.setText("X");
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(title)
                .addContainerGap(203, Short.MAX_VALUE))
            .addComponent(separator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastroSectionTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addGap(40, 40, 40)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(cadastroSectionTitle)
                .addGap(0, 0, 0)
                .addComponent(selectedIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(4, 61, 93));
        content.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSeuNome.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        lblSeuNome.setForeground(new java.awt.Color(4, 61, 93));
        lblSeuNome.setLabelFor(txtNome);
        lblSeuNome.setText("Nome");

        lblSuaEquipe.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        lblSuaEquipe.setForeground(new java.awt.Color(4, 61, 93));
        lblSuaEquipe.setLabelFor(txtEquipe);
        lblSuaEquipe.setText("Time");

        txtNome.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(4, 61, 93));
        txtNome.setBorder(null);
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtEquipe.setFont(new java.awt.Font("PT Sans", 0, 14)); // NOI18N
        txtEquipe.setForeground(new java.awt.Color(4, 61, 93));
        txtEquipe.setBorder(null);
        txtEquipe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        linha01.setBackground(new java.awt.Color(3, 46, 70));
        linha01.setForeground(new java.awt.Color(3, 46, 70));
        linha01.setText("jLabel1");
        linha01.setOpaque(true);

        linha02.setBackground(new java.awt.Color(3, 46, 70));
        linha02.setForeground(new java.awt.Color(3, 46, 70));
        linha02.setText("jLabel1");
        linha02.setOpaque(true);

        scrollPaneListaGoleiros.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneListaGoleiros.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listGoleiros.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        listGoleiros.setForeground(new java.awt.Color(4, 61, 93));
        listGoleiros.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listGoleiros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listGoleiros.setFocusable(false);
        listGoleiros.setMaximumSize(new java.awt.Dimension(50, 57));
        listGoleiros.setMinimumSize(new java.awt.Dimension(50, 57));
        listGoleiros.setPreferredSize(new java.awt.Dimension(50, 57));
        listGoleiros.setSelectionBackground(new java.awt.Color(4, 61, 93));
        listGoleiros.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listGoleiros.setVisibleRowCount(1);
        scrollPaneListaGoleiros.setViewportView(listGoleiros);

        lblGoleirosList.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        lblGoleirosList.setForeground(new java.awt.Color(4, 61, 93));
        lblGoleirosList.setLabelFor(txtNome);
        lblGoleirosList.setText("Goleiros");

        lblQuantidadeGoleiros.setFont(new java.awt.Font("PT Sans", 1, 12)); // NOI18N
        lblQuantidadeGoleiros.setForeground(new java.awt.Color(15, 89, 94));
        lblQuantidadeGoleiros.setLabelFor(txtNome);
        lblQuantidadeGoleiros.setText("*Selecione um goleiro");

        lblBatedoresDePenaltisList.setFont(new java.awt.Font("PT Sans", 1, 16)); // NOI18N
        lblBatedoresDePenaltisList.setForeground(new java.awt.Color(4, 61, 93));
        lblBatedoresDePenaltisList.setLabelFor(txtNome);
        lblBatedoresDePenaltisList.setText("Batedores de Pênaltis");

        scrollPaneListaBatedoresPenaltis.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneListaBatedoresPenaltis.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        listBatedoresPenaltis.setFont(new java.awt.Font("PT Sans", 1, 14)); // NOI18N
        listBatedoresPenaltis.setForeground(new java.awt.Color(4, 61, 93));
        listBatedoresPenaltis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 1", "Item 2", "Item 1", "Item 2", "Item 1", "Item 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBatedoresPenaltis.setFocusable(false);
        listBatedoresPenaltis.setMaximumSize(new java.awt.Dimension(50, 57));
        listBatedoresPenaltis.setMinimumSize(new java.awt.Dimension(50, 57));
        listBatedoresPenaltis.setPreferredSize(new java.awt.Dimension(50, 57));
        listBatedoresPenaltis.setSelectionBackground(new java.awt.Color(4, 61, 93));
        listBatedoresPenaltis.setSelectionForeground(new java.awt.Color(255, 255, 255));
        listBatedoresPenaltis.setVisibleRowCount(1);
        scrollPaneListaBatedoresPenaltis.setViewportView(listBatedoresPenaltis);

        lblQuantidadeBatedoresDePenaltis.setFont(new java.awt.Font("PT Sans", 1, 12)); // NOI18N
        lblQuantidadeBatedoresDePenaltis.setForeground(new java.awt.Color(15, 89, 94));
        lblQuantidadeBatedoresDePenaltis.setLabelFor(txtNome);
        lblQuantidadeBatedoresDePenaltis.setText("*Selecione quatro batedores de pênaltis");

        btnLogin.setBackground(new java.awt.Color(15, 89, 94));
        btnLogin.setFont(new java.awt.Font("PT Sans", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setFocusPainted(false);
        btnLogin.setFocusable(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(linha01, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSeuNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSuaEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGoleirosList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneListaGoleiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantidadeGoleiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(linha02, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBatedoresDePenaltisList, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneListaBatedoresPenaltis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadeBatedoresDePenaltis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeuNome)
                            .addComponent(lblGoleirosList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(linha01, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrollPaneListaGoleiros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuaEquipe)
                            .addComponent(lblQuantidadeGoleiros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(linha02, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(lblBatedoresDePenaltisList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPaneListaBatedoresPenaltis, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantidadeBatedoresDePenaltis)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        mainWindowController.btnLoginClick();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        mainWindowController.closeButtonOnClick();
    }//GEN-LAST:event_closeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel cadastroSectionTitle;
    private javax.swing.JLabel closeButton;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblBatedoresDePenaltisList;
    private javax.swing.JLabel lblGoleirosList;
    private javax.swing.JLabel lblQuantidadeBatedoresDePenaltis;
    private javax.swing.JLabel lblQuantidadeGoleiros;
    private javax.swing.JLabel lblSeuNome;
    private javax.swing.JLabel lblSuaEquipe;
    private javax.swing.JLabel linha01;
    private javax.swing.JLabel linha02;
    private javax.swing.JList<String> listBatedoresPenaltis;
    private javax.swing.JList<String> listGoleiros;
    private javax.swing.JScrollPane scrollPaneListaBatedoresPenaltis;
    private javax.swing.JScrollPane scrollPaneListaGoleiros;
    private javax.swing.JLabel selectedIndicator;
    private javax.swing.JLabel separator;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtEquipe;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getTxtEquipe() {
        return txtEquipe;
    }

    public javax.swing.JTextField getTxtNome() {
        return txtNome;
    }
}
