/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.livr.views.boundary;

import br.com.livr.views.control.ParOuImparDialogController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author victor
 */
public class ParOuImparDialog extends javax.swing.JDialog {

    private List<JRadioButton> rbParEImpar = new ArrayList<>();     
    private final Notificacao notificacao = new Notificacao();
    private final ParOuImparDialogController parOuImparDialogController = new ParOuImparDialogController(this);

    /**
     * Creates new form ParOuImparDialog
     *
     * @param parent
     * @param modal
     */
    public ParOuImparDialog(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rbParEImpar.add(rbPar);
        rbParEImpar.add(rbImpar);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupParOuImpar = new javax.swing.ButtonGroup();
        pnlContent = new javax.swing.JPanel();
        lblTituloParOuImpar = new javax.swing.JLabel();
        lblDedos = new javax.swing.JLabel();
        sliderQuantidadeDedos = new javax.swing.JSlider();
        btnJogar = new javax.swing.JButton();
        rbPar = new javax.swing.JRadioButton();
        rbImpar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(585, 240));
        setUndecorated(true);
        setResizable(false);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblTituloParOuImpar.setBackground(new java.awt.Color(255, 255, 255));
        lblTituloParOuImpar.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lblTituloParOuImpar.setForeground(new java.awt.Color(255, 102, 102));
        lblTituloParOuImpar.setText("Par ou Impar");
        lblTituloParOuImpar.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 114, 0, 37);
        pnlContent.add(lblTituloParOuImpar, gridBagConstraints);

        lblDedos.setBackground(new java.awt.Color(255, 255, 255));
        lblDedos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblDedos.setForeground(new java.awt.Color(255, 102, 102));
        lblDedos.setText("Dedos");
        lblDedos.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 12, 0, 0);
        pnlContent.add(lblDedos, gridBagConstraints);

        sliderQuantidadeDedos.setBackground(new java.awt.Color(255, 255, 255));
        sliderQuantidadeDedos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        sliderQuantidadeDedos.setForeground(new java.awt.Color(255, 102, 102));
        sliderQuantidadeDedos.setMajorTickSpacing(1);
        sliderQuantidadeDedos.setMaximum(5);
        sliderQuantidadeDedos.setMinorTickSpacing(1);
        sliderQuantidadeDedos.setPaintLabels(true);
        sliderQuantidadeDedos.setValue(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 242;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 9, 0, 0);
        pnlContent.add(sliderQuantidadeDedos, gridBagConstraints);

        btnJogar.setBackground(new java.awt.Color(255, 102, 102));
        btnJogar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJogar.setForeground(new java.awt.Color(255, 255, 255));
        btnJogar.setText("JOGAR");
        btnJogar.setBorder(null);
        btnJogar.setFocusPainted(false);
        btnJogar.setFocusable(false);
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 165, 121, 37);
        pnlContent.add(btnJogar, gridBagConstraints);

        rbPar.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupParOuImpar.add(rbPar);
        rbPar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rbPar.setForeground(new java.awt.Color(255, 102, 102));
        rbPar.setSelected(true);
        rbPar.setText("Par");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 17, 0, 130);
        pnlContent.add(rbPar, gridBagConstraints);

        rbImpar.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupParOuImpar.add(rbImpar);
        rbImpar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        rbImpar.setForeground(new java.awt.Color(255, 102, 102));
        rbImpar.setText("Ímpar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 17, 0, 130);
        pnlContent.add(rbImpar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        getParOuImparDialogController().btnJogarActionPerformed();
    }//GEN-LAST:event_btnJogarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupParOuImpar;
    private javax.swing.JButton btnJogar;
    private javax.swing.JLabel lblDedos;
    private javax.swing.JLabel lblTituloParOuImpar;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JRadioButton rbImpar;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JSlider sliderQuantidadeDedos;
    // End of variables declaration//GEN-END:variables

    public List<JRadioButton> getRbParEImpar() {
        return rbParEImpar;
    }
    
    public void setRbParEImpar(List<JRadioButton> rbParEImpar) {
        this.rbParEImpar = rbParEImpar;
    }    

    public Notificacao getNotificacao() {
        return notificacao;
    }

    public javax.swing.JSlider getSliderQuantidadeDedos() {
        return sliderQuantidadeDedos;
    }

    public javax.swing.JButton getBtnJogar() {
        return btnJogar;
    }

    public ParOuImparDialogController getParOuImparDialogController() {
        return parOuImparDialogController;
    }
}
